name: Build and Commit Vue.js Project

on:
  push:
    branches:
      - release

env:
  ENV_BUILD: production

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Node.js環境を用意してビルドを行う
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install nuxt
        run: npm install -g nuxt

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run generate

      # ビルドによって完成したファイルをdocsに移動する
      - name: Move build to docs
        run: |
          rm -rf ./docs/
          mkdir ./docs
          mv ./dist/* ./docs/

      # アンダースコアから始まるディレクトリが無視される不具合によってアイコンが404NotFoundになる
      # その不具合を避けるために、`.nojekyll`を追加する
      - name: add .nojekyll
        run: touch ./docs/.nojekyll

      # ここまでの作業をReleaseブランチ上で反映させる
      - name: Commit and push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add -A
          git commit -m "Add dist directory [skip ci]"
          git push
